[package]
authors = ["Jeff Belgum <jeffbelgum@gmail.com>"]
name = "ntplib"
version = "0.0.1"

[dependencies]
byteorder = "0.5.3"
conv = { path = "/Users/belgum/src/rust/rust-conv" }
custom_derive = "0.1.5"
error-chain = "0.5.0"
time = "0.1.35"
